version: 2

updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: weekly
    groups:
      routine-mix-updates:
        patterns: ["*"]
        update-types: ["minor", "patch"]
